---
# might be more variables to consider 
production:
  hosts:
    wjp1-confluence.extendhealth.com:
  vars:
    envir: prod
    db_user: svc-confluence
    confl_bin: atlassian-confluence-7.4.6-64x.bin

stage:
  hosts:
    wjs1-confluence.extendhealth.com:
  vars:
    envir: stage
    db_user: svc-confluence
    confl_bin: atlassian-confluence-7.4.6-64x.bin

qa:
  hosts:
    txq1-confluence.extendhealth.com:
  vars:
    envir: qa
    db_user: svc-confluence
    confl_bin: atlassian-confluence-7.4.6-64x.bin

dev:
  hosts:
    txd1-confluence.extendhealth.com:
    txd2-confluence.extendhealth.com:
    txd3-confluence.extendhealth.com:
  vars:
    envir: dev
    db_user: svc-confluence
    confl_bin: atlassian-confluence-7.4.6-64x.bin

all:  
  vars:
    software: kb
    keystore_name: "{{envir}} + {{software}}"
    confl_url: https://www.atlassian.com/software/downloads/binary/{{confl_bin}}
    ansible_ssh_pipelining: true

...