---
# the ansible_host variables probably need to be set properly
production:
  hosts:
    wjp1-confluence:
      ansible_host: wjp1-confluence.extendhealth.com
      confl_bin: atlassian-confluence-7.4.6-64x.bin
  vars:
    envir: prod

stage:
  hosts:
    wjs1-confluence:
      ansible_host: wjs1-confluence.extendhealth.com
    confl_bin: atlassian-confluence-7.4.6-64x.bin
  vars:
    envir: stage

qa:
  hosts:
    txq1-confluence:
      ansible_host: txq1-confluence.extendhealth.com
      confl_bin: atlassian-confluence-7.4.6-64x.bin
  vars:
    envir: qa

all:  
  vars:
    software: kb
    keystore_name: "{{envir}} + {{software}}"
    confl_url: https://www.atlassian.com/software/downloads/binary/{{confl_bin}}
    ansible_ssh_pipelining: true

...