---
- name: This is my testing playbook
  hosts: localhost

# - hosts: localhost
#   user: parallels
#   vars:
#     envir: qa
#     confl_bin: atlassian-confluence-7.4.6-x64.bin
#     confl_url: https://www.atlassian.com/software/confluence/downloads/binary/{{confl_bin}}
#     ansible_ssh_pipelining: true
#   become: true

# assume we already have the installer and the response.varfile
  tasks:
  - name: install confluence
    command: /var/tmp/atlassian-confluence-7.4.6-x64.bin -q -varfile /var/tmp/response.varfile
      creates=/opt/atlassian/confluence/install.reg

