---
- name: This is my testing playbook
  hosts: localhost

# - hosts: localhost
#   user: parallels
#   vars:
#     envir: qa
#     confl_bin: atlassian-confluence-7.4.6-x64.bin
#     confl_url: https://www.atlassian.com/software/confluence/downloads/binary/{{confl_bin}}
#     ansible_ssh_pipelining: true
#   become: true

  
  tasks:
  - name: download confluence installer
    get_url:
      url: "https://www.atlassian.com/software/confluence/downloads/binary/atlassian-confluence-7.4.6-x64.bin"
      dest: /var/tmp/atlassian-confluence-7.4.6-x64.bin
      mode: 0755

  - name: copy response.varfile
    copy:
      src: files/response.varfile
      dest: /var/tmp/response.varfile
    become: true

  - name: install confluence
    command: /var/tmp/atlassian-confluence-7.4.6-x64.bin -q -varfile /var/tmp/response.varfile
      creates=/opt/atlassian/confluence/install.reg