---
- name: This is a quick test playbook. I use it to quickly test modules where necessary
  hosts: txd3-confluence.extendhealth.com
  become: true

  vars_prompt:
    - name: ansible_user
      prompt: "Enter ansible user which has sudo access"
      private: no

    - name: ansible_ssh_pass
      prompt: "Enter password for ansible user"
      private: yes
    
    - name: ansible_sudo_pass
      prompt: "Enter sudo password for user"
      private: yes
  

  tasks:
  - name: copy server.xml
    copy:
      src: ../files/qa/config/server.xml
      dest: /opt/atlassian/confluence/conf/server.xml
    become: true

  - name: copy user.sh
    copy:
      src: ../files/qa/config/user.sh
      dest: /opt/atlassian/confluence/bin/user.sh
    become: true


...