---
- name: This is a quick test playbook. I use it to quickly test modules where necessary
  hosts: txd3-confluence.extendhealth.com
  become: true

  vars_prompt:
    - name: ansible_user
      prompt: "Enter ansible user which has sudo access"
      private: no

    - name: ansible_ssh_pass
      prompt: "Enter password for ansible user"
      private: yes
    
    - name: ansible_sudo_pass
      prompt: "Enter sudo password for user"
      private: yes
  

  tasks:
  # - name: copy krb5.conf file
  #   copy:
  #     src: ../files/qa/config/krb5.conf
  #     dest: /etc/krb5.conf
  #   become: true

  # - name: copy server.xml
  #   copy:
  #     src: ../files/qa/config/server.xml
  #     dest: /opt/atlassian/confluence/conf/server.xml
  #   become: true

  - name: copy confluence.cfg.xml
    copy:
      src: ../files/qa/config/confluence.cfg.xml
      dest: /var/atlassian/application-data/confluence/confluence.cfg.xml
    become: true

  # - name: permit traffic in default zone on port 8091/tcp for synchrony
  #   ansible.posix.firewalld:
  #     port: 8091/tcp
  #     permanent: yes
  #     state: enabled

  # - name: reload firewalld
  #   service:
  #     name: firewalld
  #     state: restarted

...