---
- name: Attempting an upgrade of local Confluence installation
  hosts: localhost
  vars:
    confl_bin: atlassian-confluence-7.5.0-x64.bin
    confl_url: https://www.atlassian.com/software/confluence/downloads/binary/{{confl_bin}}

  
  tasks:
  - name: stop confluence service
    service:
      name: "confluence.service"
      state: "stopped"
  
  - name: download confluence installer
    get_url:
      url: "{{confl_url}}"
      dest: /var/tmp/{{confl_bin}}
      mode: 0755

  - name: copy upgrade.varfile
    copy:
      src: ../files/common/upgrade.varfile
      dest: /var/tmp/response.varfile
    become: true

  - name: upgrade confluence
    command: /var/tmp/{{confl_bin}} -q -varfile /var/tmp/upgrade.varfile

  - name: start & enable confluence service
    service:
      name: "confluence.service"
      state: "started"
      enabled: true
      
...