---
- name: This is a quick test playbook. I use it to quickly test modules where necessary
  hosts: txd3-confluence.extendhealth.com
  become: true
  vars:
    confl_bin: atlassian-confluence-7.4.6-x64.bin

  vars_prompt:
    - name: ansible_user
      prompt: "Enter ansible user which has sudo access"
      private: no

    - name: ansible_ssh_pass
      prompt: "Enter password for ansible user"
      private: yes
      confirm: yes
    
    - name: ansible_sudo_pass
      prompt: "Enter sudo password for user"
      private: yes
      confirm: yes
  

  tasks:
  - name: download confluence installer
    get_url:
      url: "{{confl_url}}"
      dest: /var/tmp/{{confl_bin}}
      mode: 0755

...