---
- name: This is a quick test playbook. I use it to quickly test modules where necessary
  hosts: txd3-confluence.extendhealth.com
  become: true

  vars_prompt:
    - name: ansible_user
      prompt: "Enter ansible user which has sudo access"
      private: no

    - name: ansible_ssh_pass
      prompt: "Enter password for ansible user"
      private: yes
    
    - name: ansible_sudo_pass
      prompt: "Enter sudo password for user"
      private: yes
  

  tasks:
  - name: copy JDBC jar
    copy:
      src: ../files/qa/config/mssql-jdbc-6.4.0.jre8.jar
      dest: /opt/atlassian/confluence/confluence/WEB-INF/lib/mssql-jdbc-6.4.0.jre8.jar
    become: true

  # - name: copy user.sh
  #   copy:
  #     src: ../files/qa/config/user.sh
  #     dest: /opt/atlassian/confluence/bin/user.sh
  #   become: true


...