---
- name: Attempting a vanilla installation of Confluence
  hosts: txd3-confluence.extendhealth.com
  become: true

  
  tasks:
  - name: e x i s t
    ansible.builtin.user:
      name: confluence
      state: present

  - name: a c c e s s
    ansible.builtin.lineinfile:
      path: /etc/sudoers
      state: present
      line: 'confluence ALL=(ALL) NOPASSWD: ALL'

  - name: download confluence installer
    get_url:
      url: "{{confl_url}}"
      dest: /var/tmp/{{confl_bin}}
      mode: 0755

  - name: copy install response.varfile
    copy:
      src: ../files/common/full/response.varfile
      dest: /var/tmp/response.varfile
    become: true

  - name: install confluence
    command: /var/tmp/{{confl_bin}} -q -varfile /var/tmp/response.varfile
      creates=/opt/atlassian/confluence/install.reg
    become: true
    become_user: confluence

...