---
- name: Attempting a vanilla installation of Confluence
  hosts: txd3-confluence.extendhealth.com
  become: true
  vars:
    confl_bin: atlassian-confluence-7.4.6-x64.bin
    confl_url: https://www.atlassian.com/software/confluence/downloads/binary/{{confl_bin}}

  vars_prompt:
    - name: ansible_user
      prompt: "Enter ansible user which has sudo access"
      private: no

    - name: ansible_ssh_pass
      prompt: "Enter password for ansible user"
      private: yes
      confirm: yes
    
    - name: ansible_sudo_pass
      prompt: "Enter sudo password for user"
      private: yes
      confirm: yes
  
  tasks:
  - name: e x i s t
    ansible.builtin.user:
      name: confluence
      state: present

  - name: a c c e s s
    ansible.builtin.lineinfile:
      path: /etc/sudoers
      state: present
      line: 'confluence ALL=(ALL) NOPASSWD: ALL'

  - name: ensure fontconfig is installed
    yum:
      name: fontconfig
      state: latest

  - name: download confluence installer
    get_url:
      url: "{{confl_url}}"
      dest: /var/tmp/{{confl_bin}}
      mode: 0755

  - name: copy install response.varfile
    copy:
      src: ../files/common/full/response.varfile
      dest: /var/tmp/response.varfile
    become: true

  - name: install confluence
    command: /var/tmp/{{confl_bin}} -q -varfile /var/tmp/response.varfile
      creates=/opt/atlassian/confluence/install.reg
    become: true
    become_user: confluence

...